### ISSUE TITLE
En lugar de incluir implementacion Oracle debería ser JDBC

### ISSUE THREAD

**Issue by jtpadilla** [universitatjaumei/uji-control-domain#2]
Me parece razonable que si los drivers son JDBC esta implementacion deberia de soportar varios sabores de esta API.

Si no queremos hacerlo completamente generico, poder soportar en las propiedades (UI) los mas comunes (Oracle, MySql, Google SQL Storage, etc).

El proyecto de la implementacion deberia entonces llamarse **es.uji.control.domain.jdc** en lugar de **es.uji.control.domain.oracle**

Como lo ves ?

**Comment by tadeoj** [comment]
Perfecto, tiene más sentido.

**Comment by tadeoj** [comment]
He realizado el cambio de nombre ahora el proyecto se llama **es.uji.control.domain.jdbc**.

**Comment by tadeoj** [comment]
Cierro la tarea #2.
